extends SceneTree

const FixtureScript = preload("res://tests/helpers/proxy_runtime_fixture.gd")
const AutostartServiceScript = preload("res://scripts/modules/system/autostart_service.gd")
const SubscriptionProfileFactoryScript = preload("res://scripts/modules/subscription/subscription_profile_factory.gd")

func _init() -> void:
	var fixture = FixtureScript.new()
	root.add_child(fixture)
	fixture.initialize()
	await process_frame
	var config = fixture.config()
	var subscription = fixture.subscription
	var autostart = AutostartServiceScript.new()
	var parser = subscription.v2_parser
	var profile_factory = SubscriptionProfileFactoryScript.new()
	assert(config.DEFAULT_CONTROLLER_PORT == 19090)
	assert(config.DEFAULT_MIXED_PORT == 7890)
	assert(config.controller_port() == 19090)
	assert(config.mixed_port() == 7890)
	assert(config.has_core())
	assert(fixture.proxy.recovery.DELAYS == [1.0, 3.0, 8.0])
	assert(config.core_path().contains("runtime"))
	assert(FileAccess.file_exists(subscription.profile_path()))
	var profile := FileAccess.get_file_as_string(subscription.profile_path())
	assert(profile.contains("mixed-port: 7890"))
	assert(profile.contains("MATCH,六角选择"))
	var routing_rules: String = profile_factory.generated_routing_rules()
	assert(routing_rules.contains("IP-CIDR,127.0.0.0/8,DIRECT,no-resolve"))
	assert(routing_rules.contains("IP-CIDR,192.168.0.0/16,DIRECT,no-resolve"))
	assert(routing_rules.contains("IP-CIDR6,::1/128,DIRECT,no-resolve"))
	assert(routing_rules.contains("RULE-SET,hexagon-cn-domain,DIRECT"))
	assert(routing_rules.contains("RULE-SET,hexagon-cn-ip,DIRECT,no-resolve"))
	assert(routing_rules.ends_with("MATCH,六角选择\n"))
	assert(profile_factory.generated_rule_providers().contains("format: mrs"))
	assert(FileAccess.file_exists(config.runtime_dir().path_join("rules/geosite-cn.mrs")))
	assert(FileAccess.file_exists(config.runtime_dir().path_join("rules/geoip-cn.mrs")))
	assert(parser.looks_like_base64("dmxlc3M6Ly9leGFtcGxl"))
	assert(not parser.looks_like_base64("not base64!"))
	var base64_sample := Marshalls.utf8_to_base64("vless://example")
	assert(parser.decode_base64_text(base64_sample) == "vless://example")
	assert(autostart.autostart_command().contains("--tray-start"))
	assert(autostart.autostart_command().contains("--path"))
	assert(bool(fixture.proxy.validator.validate().get("ok", false)))
	fixture.proxy.api_secret_changed.emit("test-secret")
	assert(fixture.api.api_secret == "test-secret")
	autostart.free()
	fixture.shutdown()
	await process_frame
	print("PASS: HexagonProxy基础配置与模块契约")
	quit(0)
